version: 2
updates:
  - package-ecosystem: pip
    commit-message:
      prefix: feat
      include: scope
    groups:
       all:
         applies-to: version-updates
         patterns:
           - "*"
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: cpr_sdk
    reviewers:
      - climatepolicyradar/deng
  - package-ecosystem: github-actions
    commit-message:
      prefix: feat
      include: scope
    groups:
       all:
         applies-to: version-updates
         patterns:
           - "*"
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: cpr_sdk
    reviewers:
      - climatepolicyradar/deng
  - package-ecosystem: pip
    commit-message:
      prefix: feat
      include: scope
    groups:
       all:
         applies-to: version-updates
         patterns:
           - "*"
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: cpr_sdk
    target-branch: main
    reviewers:
      - climatepolicyradar/deng
