name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  build-start-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run:  |
          cp .env.example .env
          make build

      - name: Install latest Vespa CLI
        env:
          VESPA_CLI_VERSION: "8.326.37"
        run: |
          mkdir vespa-cli
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | \
            tar -zxf - -C vespa-cli --strip-component=1
          echo "vespa-cli/bin" >> $GITHUB_PATH

      - name: Setup Vespa Test Instance
        run:  make vespa_setup

      - name: Run Tests
        run:  make test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.1

      - name: Push Images to ECR
        run: |
          .github/retag-and-push.sh navigator-search-indexer latest
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
